project_id = "ifshrmdofwrjyqostgbl"

[functions.paystack-webhook]
verify_jwt = false

[functions.flutterwave-webhook]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.initialize-payment]
verify_jwt = false
